import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";

const orbitron = localFont({
  src: [
    {
      path: "./fonts/Orbitron.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-orbitron",
});

const calSans = localFont({
  src: [
    {
      path: "./fonts/CalSans.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-cal-sans",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${calSans.variable} ${roboto.variable} antialiased`}
      >
        {children}d
      </body>
    </html>
  );
}
